version: '3.8'

services:
  xclone_express:
    build: .
    image: xclone_express:2.1.1
    expose:
      - '9090'
    volumes:
      - ./uploads:/app/uploads
      - ./global-bundle.pem:/app/global-bundle.pem
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=9090
      - SSL=false
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    entrypoint: ['sh', '/usr/local/bin/docker-entrypoint.sh']
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - xclone_express
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
