version: '3.8'

services:
  xclone_express:
    build: .
    image: xclone_express:1.0.0
    expose:
      - '9090'
    volumes:
      - ./uploads:/app/uploads
      - ./global-bundle.pem:/app/global-bundle.pem
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=9090
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - xclone_express
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
