name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_ID }}@${{ secrets.EC2_SSH_DOMAIN }} "mkdir -p /app/xclone_express"
          scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.EC2_SSH_ID }}@${{ secrets.EC2_SSH_DOMAIN }}:/app/xclone_express

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_ID }}@${{ secrets.EC2_SSH_DOMAIN }} << 'EOF'
            cd /app/xclone_express
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
